name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests 
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          start: npm run open

      - name: Uploading artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30